# Generated by Django 3.0.3 on 2020-02-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ofrecer_viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('lugar_de_partida', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
                ('Hora', models.DateTimeField()),
                ('Asientos_Disponibles', models.IntegerField()),
                ('Costo', models.IntegerField()),
            ],
        ),
    ]
