# Generated by Django 3.0.3 on 2020-02-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitar_viaje', '0001_initial'),
        ('ofrecer_viaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofrecer_viaje',
            name='Persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitar_viaje.Persona'),
        ),
    ]
